apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3bear.fullname" . }}
  labels:
    {{- include "s3bear.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  DATABASE_URL_SYNC: {{ .Values.secrets.databaseUrlSync | quote }}
  AZURE_TENANT_ID: {{ .Values.secrets.azureTenantId | quote }}
  AZURE_CLIENT_ID: {{ .Values.secrets.azureClientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.secrets.azureClientSecret | quote }}
  AZURE_REDIRECT_URI: {{ .Values.secrets.azureRedirectUri | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  DEFAULT_ADMIN_EMAIL: {{ .Values.secrets.defaultAdminEmail | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.defaultAdminPassword | quote }}
