apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3bear.fullname" . }}-backend
  labels:
    {{- include "s3bear.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
      name: http
  selector:
    {{- include "s3bear.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3bear.fullname" . }}-frontend
  labels:
    {{- include "s3bear.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
      name: http
  selector:
    {{- include "s3bear.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
