apiVersion: v2
name: s3bear
description: s3BEAR — secure S3 web panel with Azure Entra auth
type: application
version: 1.0.3
appVersion: "1.0.3"
keywords:
  - s3
  - storage
  - gateway
maintainers:
  - name: team
